version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: northgrove/registeraadapp-ci
    steps:
      - run: node app.js

    #working_directory: github.com/navikt/iac

    #steps:
    #  - checkout

    
    #working_directory: /
workflows:
  version: 2
  build:
    jobs:
      - build
    