version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.0
    #  - image: northgrove/registeraadapp-ci

    steps:
      - checkout
      #- run: npm install
      #- run: node ~/project/app.js
      - setup_remote_docker
      - run: |
          docker create -v /cfg --name registeraadapp northgrove/registeraadapp-ci /bin/true
          docker cp ~/project/applications.yaml registeraadapp:/cfg
          docker run --volumes-from registeraadapp northgrove/registeraadapp-ci

  

  

          

    
    #working_directory: github.com/navikt/iac

    #steps:#
    # - checkout

    
    #working_directory: /

    