version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.0
    #  - image: northgrove/registeraadapp-ci

    steps:
      - checkout
      #- run: npm install
      #- run: node ~/project/app.js
      - setup_remote_docker
      - run: |
          apiURI=$apiURI
          docker create -v /app --name registeraadapp northgrove/registeraadapp-ci /bin/true
          docker cp ~/project/applicationsQ.yaml registeraadapp:/app
          docker cp ~/project/applicationsP.yaml registeraadapp:/app
          docker run --volumes-from registeraadapp -e apiURIQ=$apiURIQ apiURIP=$apiURIP northgrove/registeraadapp-ci
          
  

  

          

    
    #working_directory: github.com/navikt/iac

    #steps:#
    # - checkout

    
    #working_directory: /

    