version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.0
      - image: northgrove/registeraadapp-ci

    steps:
      - checkout
      - run: node ~/project/app.js

  

  

          

    
    #working_directory: github.com/navikt/iac

    #steps:#
    # - checkout

    
    #working_directory: /

    