version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.0

    steps:
      - checkout
  
  apply:
    docker:
      - image: northgrove/registeraadapp-ci
    
    steps:
      - run:
    
    #working_directory: github.com/navikt/iac

    #steps:#
    # - checkout

    
    #working_directory: /
workflows:
  version: 2
  build:
    jobs:
      - build
      - apply:
          requires:
            - build
    