version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: northgrove/registeraadapp-ci
    steps:
      - checkout

    #working_directory: github.com/navikt/iac

    #steps:
    #  - checkout

    
    #working_directory: /
    